// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAaGw2lHxJ57ouyQV3w7OuMd_sqlcOHFA',
    appId: '1:944539310162:web:799cc801702dab7f95678b',
    messagingSenderId: '944539310162',
    projectId: 'e-commerce-dd20f',
    authDomain: 'e-commerce-dd20f.firebaseapp.com',
    storageBucket: 'e-commerce-dd20f.firebasestorage.app',
    measurementId: 'G-BJS71SQQYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUOI2aWai01p8yYEormbo0tTg8Gd7VGE',
    appId: '1:944539310162:android:175dacf528d7fb2195678b',
    messagingSenderId: '944539310162',
    projectId: 'e-commerce-dd20f',
    storageBucket: 'e-commerce-dd20f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzlFeThHxLUUpyhNNq3qaxfflIrhQUQas',
    appId: '1:944539310162:ios:a595ed91f9b4022795678b',
    messagingSenderId: '944539310162',
    projectId: 'e-commerce-dd20f',
    storageBucket: 'e-commerce-dd20f.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzlFeThHxLUUpyhNNq3qaxfflIrhQUQas',
    appId: '1:944539310162:ios:a595ed91f9b4022795678b',
    messagingSenderId: '944539310162',
    projectId: 'e-commerce-dd20f',
    storageBucket: 'e-commerce-dd20f.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAaGw2lHxJ57ouyQV3w7OuMd_sqlcOHFA',
    appId: '1:944539310162:web:768255972e458efe95678b',
    messagingSenderId: '944539310162',
    projectId: 'e-commerce-dd20f',
    authDomain: 'e-commerce-dd20f.firebaseapp.com',
    storageBucket: 'e-commerce-dd20f.firebasestorage.app',
    measurementId: 'G-K0QYFSHSTD',
  );
}
